# Vapez SMP — Purpur 1.21.8
# MOTD is shown to both Java and (via Geyser) Bedrock.
motd=§b§lVapez SMP §8• §dAetherium §8• §71.21 Cross-Play
server-name=Vapez SMP
server-port=25565
query.port=25565
enable-query=true
enable-rcon=false
rcon.port=25575
rcon.password=
broadcast-rcon-to-ops=true
broadcast-console-to-ops=true

online-mode=true
prevent-proxy-connections=true
enforce-secure-profile=true
enforce-whitelist=false
white-list=false
max-players=200
player-idle-timeout=0
pause-when-empty-seconds=-1

gamemode=survival
force-gamemode=false
difficulty=hard
hardcore=false
pvp=true
spawn-monsters=true
spawn-animals=true
spawn-npcs=true
generate-structures=true
allow-nether=true
allow-flight=true
enable-command-block=false
enable-status=true
hide-online-players=false

# WorldGuard + VapezCore handle spawn. Vanilla spawn protection fights FAWE.
spawn-protection=0
max-world-size=29999984
view-distance=8
simulation-distance=6
entity-broadcast-range-percentage=100

level-name=world
level-type=minecraft\:normal
level-seed=
generator-settings={}
max-build-height=320

# Initial vanilla border is overwritten by VapezCore to diameter 10000.
# Do not set max-world-size below the Far Lands expansion target.

network-compression-threshold=256
rate-limit=0
use-native-transport=true
sync-chunk-writes=false
max-tick-time=60000
max-chained-neighbor-updates=1000000

function-permission-level=2
op-permission-level=4
enable-jmx-monitoring=false
log-ips=true
debug=false

resource-pack=
resource-pack-prompt=§bVapez Aetherium resource pack — required for custom ore/gear.
resource-pack-sha1=
require-resource-pack=false
resource-pack-id=

text-filtering-config=
accepts-transfers=false
region-file-compression=deflate
bug-report-link=
initial-enabled-packs=vanilla
initial-disabled-packs=
