#!/usr/bin/env bash
# Download Purpur, third-party plugins (official sources only), datapacks, and assemble runtime/.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PACK="${ROOT}/pack"
RUNTIME="${PACK}/runtime"
MC_VERSION="${MC_VERSION:-1.21.8}"
mkdir -p "${RUNTIME}/plugins" "${RUNTIME}/config" "${RUNTIME}/world/datapacks" \
         "${RUNTIME}/plugins/Geyser-Spigot/custom_mappings" \
         "${RUNTIME}/plugins/Geyser-Spigot/packs"

echo "==> Checking Java 21+"
java -version 2>&1 | head -n1

echo "==> Building VapezCore"
(cd "${ROOT}/plugin" && mvn -q -DskipTests package)
cp -f "${ROOT}/plugin/target/VapezCore-1.0.0.jar" "${PACK}/plugins/VapezCore-1.0.0.jar"

echo "==> Generating textures / schematic / resource packs"
python3 "${ROOT}/scripts/generate_assets.py"

echo "==> Downloading Purpur ${MC_VERSION}"
curl -fL "https://api.purpurmc.org/v2/purpur/${MC_VERSION}/latest/download" \
  -o "${RUNTIME}/purpur-${MC_VERSION}.jar"

download() {
  local url="$1" dest="$2"
  echo "  GET ${url}"
  curl -fL --retry 4 --retry-delay 4 "${url}" -o "${dest}"
}

echo "==> Downloading official plugins (no redistributed paid jars)"
download "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot" \
  "${RUNTIME}/plugins/Geyser-Spigot.jar"
download "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot" \
  "${RUNTIME}/plugins/floodgate-spigot.jar"

# Modrinth API helper
modrinth() {
  local project="$1" dest="$2" loader="${3:-paper}" game="${4:-${MC_VERSION}}"
  local url
  url="$(curl -fsSL "https://api.modrinth.com/v2/project/${project}/version?loaders=%5B%22${loader}%22%5D&game_versions=%5B%22${game}%22%5D" \
    | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d[0]["files"][0]["url"] if d else "")')"
  if [[ -z "${url}" ]]; then
    echo "  ! No Modrinth file for ${project} (${loader}/${game}) — trying without game filter"
    url="$(curl -fsSL "https://api.modrinth.com/v2/project/${project}/version?loaders=%5B%22${loader}%22%5D" \
      | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d[0]["files"][0]["url"] if d else "")')"
  fi
  if [[ -z "${url}" ]]; then
    echo "  !! SKIP ${project} — download manually (see docs/INSTALL.md)"
    return 0
  fi
  download "${url}" "${dest}"
}

modrinth viaversion "${RUNTIME}/plugins/ViaVersion.jar"
modrinth viabackwards "${RUNTIME}/plugins/ViaBackwards.jar"
modrinth placeholderapi "${RUNTIME}/plugins/PlaceholderAPI.jar"
modrinth decentholograms "${RUNTIME}/plugins/DecentHolograms.jar"
modrinth chunky "${RUNTIME}/plugins/Chunky.jar"
modrinth luckperms "${RUNTIME}/plugins/LuckPerms.jar" paper "${MC_VERSION}"
modrinth spark "${RUNTIME}/plugins/spark.jar"
modrinth coreprotect "${RUNTIME}/plugins/CoreProtect.jar"
modrinth worldedit "${RUNTIME}/plugins/WorldEdit.jar" paper "${MC_VERSION}"
modrinth bluemap "${RUNTIME}/plugins/BlueMap.jar" paper "${MC_VERSION}" || true

# EngineHub / Hangar / GitHub known URLs
download "https://github.com/MilkBowl/Vault/releases/latest/download/Vault.jar" \
  "${RUNTIME}/plugins/Vault.jar" || echo "  !! Vault: download from https://www.spigotmc.org/resources/vault.34315/"

echo "==> EssentialsX"
modrinth essentialsx "${RUNTIME}/plugins/EssentialsX.jar" paper "${MC_VERSION}" || true

echo "==> Stardust Labs datapacks (Terralith, Structory, Towns and Towers)"
modrinth terralith "${RUNTIME}/world/datapacks/Terralith.zip" minecraft "${MC_VERSION}"
modrinth structory "${RUNTIME}/world/datapacks/Structory.zip" minecraft "${MC_VERSION}"
modrinth towns-and-towers "${RUNTIME}/world/datapacks/TownsAndTowers.zip" minecraft "${MC_VERSION}"

echo "==> Copying configs and Vapez datapack/resource pack"
cp -a "${PACK}/server.properties" "${PACK}/bukkit.yml" "${PACK}/spigot.yml" "${PACK}/purpur.yml" "${RUNTIME}/"
cp -a "${PACK}/config/." "${RUNTIME}/config/"
cp -a "${PACK}/plugins/." "${RUNTIME}/plugins/"
cp -a "${PACK}/datapacks/vapez-aetherium" "${RUNTIME}/world/datapacks/"
cp -f "${PACK}/eula.txt.example" "${RUNTIME}/eula.txt"
cp -f "${PACK}/start.sh" "${PACK}/start.bat" "${RUNTIME}/"
chmod +x "${RUNTIME}/start.sh"

# Floodgate key is generated by Geyser on first boot; copy it into Geyser after first start.
echo "==> Done. Next:"
echo "  1. Edit ${RUNTIME}/eula.txt  (eula=true)"
echo "  2. cd ${RUNTIME} && ./start.sh"
echo "  3. After first stop: copy plugins/floodgate/key.pem to plugins/Geyser-Spigot/key.pem"
echo "  4. Host pack/resourcepack/Vapez-Aetherium.zip (see docs/CROSSPLAY.md)"
echo "  5. Run scripts/pregen.sh once the console is idle"
echo
echo "Paid / optional jars you must fetch yourself (not redistributed):"
echo "  FastAsyncWorldEdit, WorldGuard, ProtocolLib, ZNPCsPlus, ExcellentCrates,"
echo "  AuctionHouse, PlayerWarps, Oraxen/ItemsAdder, UltimateDonutSMP (do NOT pirate)."
echo "  VapezCore already implements shop/AH/warps/lifesteal/levels/crates/kit."
